import type { Product } from "@prisma/client";
import type { FeedType } from "../types/product";
import {
  escapeXml,
  formatFeedPrice,
  toGoogleAvailability,
} from "../utils/product";
import { listProducts } from "./product.server";
import { logFeedRequest } from "./feed-request.server";

interface FeedChannelMeta {
  title: string;
  link: string;
  description: string;
}

const FEED_CHANNEL_META: Record<FeedType, FeedChannelMeta> = {
  GOOGLE: {
    title: "Mango Product Feed - Google Shopping",
    link: "https://mango-store.example.com",
    description: "Google Merchant Center product feed generated by Mango Product Feed",
  },
  META: {
    title: "Mango Product Feed - Meta Catalog",
    link: "https://mango-store.example.com",
    description: "Meta Commerce catalog product feed generated by Mango Product Feed",
  },
  TIKTOK: {
    title: "Mango Product Feed - TikTok Catalog",
    link: "https://mango-store.example.com",
    description: "TikTok Catalog product feed generated by Mango Product Feed",
  },
  PINTEREST: {
    title: "Mango Product Feed - Pinterest Catalog",
    link: "https://mango-store.example.com",
    description: "Pinterest Catalog product feed generated by Mango Product Feed",
  },
  SNAPCHAT: {
    title: "Mango Product Feed - Snapchat Catalog",
    link: "https://mango-store.example.com",
    description: "Snapchat Catalog product feed generated by Mango Product Feed",
  },
  CUSTOM: {
    title: "Mango Product Feed - Custom XML",
    link: "https://mango-store.example.com",
    description: "Custom XML product feed generated by Mango Product Feed",
  },
};

function buildOptionalFields(product: Product, feedType: FeedType): string {
  const fields: string[] = [];

  if (product.brand) {
    fields.push(`      <g:brand>${escapeXml(product.brand)}</g:brand>`);
  }
  if (product.category) {
    fields.push(
      `      <g:google_product_category>${escapeXml(product.category)}</g:google_product_category>`,
    );
  }
  if (product.productType) {
    fields.push(
      `      <g:product_type>${escapeXml(product.productType)}</g:product_type>`,
    );
  }
  if (product.sku) {
    fields.push(`      <g:mpn>${escapeXml(product.sku)}</g:mpn>`);
  }

  const price = formatFeedPrice(Number(product.price));
  fields.push(`      <g:price>${price}</g:price>`);

  if (product.salePrice) {
    fields.push(
      `      <g:sale_price>${formatFeedPrice(Number(product.salePrice))}</g:sale_price>`,
    );
  }

  if (feedType === "META") {
    fields.push(`      <g:condition>new</g:condition>`);
  }

  if (feedType === "TIKTOK" || feedType === "PINTEREST") {
    fields.push(`      <g:condition>new</g:condition>`);
  }

  if (feedType === "TIKTOK") {
    fields.push(`      <g:identifier_exists>false</g:identifier_exists>`);
  }

  if (feedType === "SNAPCHAT") {
    fields.push(`      <g:condition>NEW</g:condition>`);
  }

  return fields.filter(Boolean).join("\n");
}

function buildFeedItem(product: Product, feedType: FeedType): string {
  const availability = toGoogleAvailability(product.availability);
  const optionalFields = buildOptionalFields(product, feedType);

  return `    <item>
      <g:id>${escapeXml(product.sku)}</g:id>
      <title>${escapeXml(product.title)}</title>
      <description>${escapeXml(product.description.slice(0, 5000))}</description>
      <link>${escapeXml(product.productUrl)}</link>
      <g:image_link>${escapeXml(product.imageUrl)}</g:image_link>
      <g:availability>${availability}</g:availability>
${optionalFields}
    </item>`;
}

export function buildFeedXml(products: Product[], feedType: FeedType): string {
  const meta = FEED_CHANNEL_META[feedType];
  const items = products.map((product) => buildFeedItem(product, feedType)).join("\n");

  return `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:g="http://base.google.com/ns/1.0">
  <channel>
    <title>${escapeXml(meta.title)}</title>
    <link>${escapeXml(meta.link)}</link>
    <description>${escapeXml(meta.description)}</description>
    <lastBuildDate>${new Date().toUTCString()}</lastBuildDate>
${items}
  </channel>
</rss>`;
}

export async function generateFeed(
  feedType: FeedType,
  shopId?: string | null,
): Promise<string> {
  const { getDefaultFeedConfig } = await import("./feed-config.server");
  const { buildFeedXmlFromConfig } = await import("./feed-stream.server");

  const config = await getDefaultFeedConfig(feedType, shopId);
  if (config) {
    const xml = await buildFeedXmlFromConfig(config);
    await logFeedRequest(feedType, await countProductsInXml(xml), "SUCCESS");
    return xml;
  }

  const products = await listProducts(shopId);
  const xml = buildFeedXml(products, feedType);
  await logFeedRequest(feedType, products.length, "SUCCESS");
  return xml;
}

export async function previewFeed(
  feedType: FeedType,
  shopId?: string | null,
): Promise<string> {
  const { getDefaultFeedConfig } = await import("./feed-config.server");
  const { buildFeedXmlFromConfig } = await import("./feed-stream.server");

  const config = await getDefaultFeedConfig(feedType, shopId);
  if (config) {
    return buildFeedXmlFromConfig(config);
  }

  const products = await listProducts(shopId);
  return buildFeedXml(products, feedType);
}

function countProductsInXml(xml: string): number {
  return (xml.match(/<item>/g) ?? []).length;
}
