import type { FeedConfig, FeedType, Product } from "@prisma/client";
import {
  escapeXml,
  formatFeedPrice,
  toGoogleAvailability,
} from "../utils/product";
import { applyCategoryMapping } from "./category-mapping.server";
import { convertProductPrice } from "./currency.server";
import type { FeedRenderContext } from "../types/feed-channels";

export const FEED_CHANNEL_LABELS: Record<FeedType, string> = {
  GOOGLE: "Google Shopping",
  META: "Meta Catalog",
  TIKTOK: "TikTok Catalog",
  PINTEREST: "Pinterest Catalog",
  SNAPCHAT: "Snapchat Catalog",
  CUSTOM: "Custom XML",
};

export const FEED_LEGACY_PATHS: Record<FeedType, string> = {
  GOOGLE: "/feed/google.xml",
  META: "/feed/meta.xml",
  TIKTOK: "/feed/tiktok.xml",
  PINTEREST: "/feed/pinterest.xml",
  SNAPCHAT: "/feed/snapchat.xml",
  CUSTOM: "/feed/custom.xml",
};

export function getChannelMeta(
  feedType: FeedType,
  feedName: string,
  storeName: string,
  storeUrl: string,
) {
  return {
    title: `${feedName} - ${FEED_CHANNEL_LABELS[feedType]}`,
    link: storeUrl,
    description: `${FEED_CHANNEL_LABELS[feedType]} product feed generated by Mango Product Feed for ${storeName}`,
  };
}

export function buildStandardFeedHeader(meta: {
  title: string;
  link: string;
  description: string;
}): string {
  return `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:g="http://base.google.com/ns/1.0">
  <channel>
    <title>${escapeXml(meta.title)}</title>
    <link>${escapeXml(meta.link)}</link>
    <description>${escapeXml(meta.description)}</description>
    <lastBuildDate>${new Date().toUTCString()}</lastBuildDate>
`;
}

export const STANDARD_FEED_FOOTER = `  </channel>
</rss>`;

function resolveProductFields(
  product: Product,
  ctx: FeedRenderContext,
): Product {
  let resolved = { ...product };

  if (product.aiOptimizedTitle) {
    resolved = { ...resolved, title: product.aiOptimizedTitle };
  }
  if (product.aiOptimizedDescription) {
    resolved = { ...resolved, description: product.aiOptimizedDescription };
  }

  if (ctx.targetCurrency && ctx.targetCurrency !== product.currencyCode) {
    const converted = convertProductPrice(product, ctx.targetCurrency);
    resolved = {
      ...resolved,
      price: converted.price,
      salePrice: converted.salePrice,
      currencyCode: ctx.targetCurrency,
    };
  }

  return resolved;
}

async function resolveCategory(
  product: Product,
  ctx: FeedRenderContext,
): Promise<string> {
  if (!product.category || !ctx.shopId) return product.category;
  return applyCategoryMapping(
    ctx.shopId,
    ctx.feedType,
    product.category,
  );
}

function buildChannelSpecificFields(
  product: Product,
  feedType: FeedType,
  category: string,
): string {
  const fields: string[] = [];

  if (product.brand) {
    fields.push(`      <g:brand>${escapeXml(product.brand)}</g:brand>`);
  }

  if (category) {
    fields.push(
      `      <g:google_product_category>${escapeXml(category)}</g:google_product_category>`,
    );
  }

  if (product.productType) {
    fields.push(
      `      <g:product_type>${escapeXml(product.productType)}</g:product_type>`,
    );
  }

  if (product.sku) {
    fields.push(`      <g:mpn>${escapeXml(product.sku)}</g:mpn>`);
  }

  if (product.gtin) {
    fields.push(`      <g:gtin>${escapeXml(product.gtin)}</g:gtin>`);
  }

  const currency = product.currencyCode || "USD";
  fields.push(
    `      <g:price>${formatFeedPrice(Number(product.price), currency)}</g:price>`,
  );

  if (product.salePrice) {
    fields.push(
      `      <g:sale_price>${formatFeedPrice(Number(product.salePrice), currency)}</g:sale_price>`,
    );
  }

  if (feedType === "META" || feedType === "TIKTOK" || feedType === "PINTEREST") {
    fields.push(`      <g:condition>new</g:condition>`);
  }

  if (feedType === "TIKTOK") {
    fields.push(
      `      <g:identifier_exists>${product.gtin ? "true" : "false"}</g:identifier_exists>`,
    );
  }

  if (feedType === "PINTEREST") {
    fields.push(`      <g:product_type>${escapeXml(product.productType || "Product")}</g:product_type>`);
  }

  if (feedType === "SNAPCHAT") {
    fields.push(`      <g:condition>NEW</g:condition>`);
    if (product.countryCode) {
      fields.push(`      <g:country>${escapeXml(product.countryCode)}</g:country>`);
    }
  }

  return fields.join("\n");
}

export async function buildFeedItemXml(
  product: Product,
  ctx: FeedRenderContext,
): Promise<string> {
  const resolved = resolveProductFields(product, ctx);
  const category = await resolveCategory(resolved, ctx);
  const availability = toGoogleAvailability(resolved.availability);
  const optionalFields = buildChannelSpecificFields(
    resolved,
    ctx.feedType,
    category,
  );

  if (ctx.customTemplate) {
    return renderCustomTemplate(ctx.customTemplate, resolved, {
      category,
      availability,
      currency: resolved.currencyCode || "USD",
    });
  }

  return `    <item>
      <g:id>${escapeXml(resolved.sku)}</g:id>
      <title>${escapeXml(resolved.title)}</title>
      <description>${escapeXml(resolved.description.slice(0, 5000))}</description>
      <link>${escapeXml(resolved.productUrl)}</link>
      <g:image_link>${escapeXml(resolved.imageUrl)}</g:image_link>
      <g:availability>${availability}</g:availability>
${optionalFields}
    </item>`;
}

function renderCustomTemplate(
  template: string,
  product: Product,
  extras: { category: string; availability: string; currency: string },
): string {
  const replacements: Record<string, string> = {
    "{{id}}": escapeXml(product.sku),
    "{{title}}": escapeXml(product.title),
    "{{description}}": escapeXml(product.description.slice(0, 5000)),
    "{{link}}": escapeXml(product.productUrl),
    "{{image}}": escapeXml(product.imageUrl),
    "{{price}}": formatFeedPrice(Number(product.price), extras.currency),
    "{{sale_price}}": product.salePrice
      ? formatFeedPrice(Number(product.salePrice), extras.currency)
      : "",
    "{{brand}}": escapeXml(product.brand),
    "{{category}}": escapeXml(extras.category),
    "{{availability}}": extras.availability,
    "{{sku}}": escapeXml(product.sku),
    "{{gtin}}": escapeXml(product.gtin ?? ""),
  };

  let rendered = template;
  for (const [key, value] of Object.entries(replacements)) {
    rendered = rendered.replaceAll(key, value);
  }
  return rendered;
}

export function isFeedExpired(config: Pick<FeedConfig, "expiresAt">): boolean {
  if (!config.expiresAt) return false;
  return config.expiresAt.getTime() < Date.now();
}
